# Documentation here: https://github.com/marketplace/actions/auto-request-review
reviewers:
  defaults:
      - EmmanuelDestin21
      - tommyd1123
      - asherblooom
      - Napatsiri4869 
      - yyyzz23570
      - Penny822
      - KieranDunningBristol
      
options:
  ignore_draft: true
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  # number_of_reviewers: 3

  # If it's true, the last matching files-change pattern takes the most precedence (CODEOWNERS-compatible)
  # See https://github.com/necojackarc/auto-request-review/pull/80 for more details.
  last_files_match_only: false
